const verbs = [
    "cours",
    "saute",
    "nage",
    "mange",
    "dors",
    "lis",
    "écris",
    "danse",
    "chante",
    "parle",
    "joue",
    "travaille",
    "étudie",
    "conduis",
    "vole",
    "grimpe",
    "ris",
    "pleure",
    "pense",
    "marche"
];

const famousNames = [
    "Elon Musk",
    "Jeff Bezos",
    "Oprah Winfrey",
    "Beyoncé Knowles",
    "Dwayne 'The Rock' Johnson",
    "Taylor Swift",
    "Kanye West",
    "Serena Williams",
    "LeBron James",
    "Billie Eilish",
    "Ariana Grande",
    "Tom Hanks",
    "Jennifer Lawrence",
    "Zendaya",
    "Emma Watson",
    "Virat Kohli",
    "Cristiano Ronaldo",
    "Lionel Messi",
    "Greta Thunberg",
    "Malala Yousafzai",
];

const strangePlaces = [
    "Forêt de Brume Éternelle",
    "Les Cavernes de Cristal",
    "Les Îles Flottantes",
    "Désert des Sables Murmureurs",
    "Le Bosquet Enchanté",
    "Lac du Miroir Mystique",
    "Labyrinthe Perdu",
    "Ruines du Château Abandonné",
    "Le Sanctuaire de la Cascade Cachée",
    "Gouffre des Gobelins",
    "Abîme d'Émeraude",
    "Le Creux de la Sorcière",
    "Le Plateau Éthéré",
    "Le Volcan de la Respiration du Dragon",
    "Dimension de l'Éternité",
    "Le Jardin Secret des Lucioles",
];


export { famousNames, verbs, strangePlaces }